# Generated by Django 3.2.4 on 2021-06-13 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20210611_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='word_count',
        ),
    ]
