# Generated by Django 3.2.4 on 2021-06-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_remove_projects_word_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
    ]
