# Generated by Django 3.2.4 on 2021-08-05 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_users_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='word_count',
            new_name='words',
        ),
    ]
